---
title: "Making a better chart"
output: html_notebook
---

A  

```{r}
library(tidyverse); library(ggthemes); library(ggalluvial); library(scales)
```



```{r}
raw_cpl <- read_csv(file = 'coupling.csv', col_types = 'iiiiiiiiii') %>%
  filter(!is.na(Year))
```


```{r}
raw_cpl %>%
  ggplot(mapping = aes(x = Year)) +
  geom_line(mapping = aes(y = Online, color = 'online')) +
  geom_line(mapping = aes(y = Bar_rest, color = 'bar or rest')) +
  geom_line(mapping = aes(y = Friends)) +
  geom_line(mapping = aes(y = Work)) +
  geom_line(mapping = aes(y = Family)) +
  geom_line(mapping = aes(y = School)) +
  geom_line(mapping = aes(y = College)) +
  geom_line(mapping = aes(y = Church)) +
  geom_line(mapping = aes(y = Neighbors))

fixed_cpl <- raw_cpl

for(i in 2:10) {
  for(j in 1:17) {
  fixed_cpl[j,i] <- raw_cpl[j,i] / (sum(raw_cpl[j,] %>% select(2:10)))
  }
}

sum(raw_cpl[1,] %>% select(i:10))

fixed_cpl %>%
  gather(-Year, key = 'meeting_place', value = 'share') %>%
  arrange(Year, meeting_place) %>%
  ggplot(mapping = aes(x = Year, y = share, fill = meeting_place, na.rm = T)) +
  geom_area(color = 'black', size = 1) +
  scale_y_continuous(labels = percent_format(accuracy = 1)) +
  scale_fill_manual(values=c('red', 'orange', 'yellow', 'green4', 'turquoise', 'blue', 'slateblue', 'purple4', 'darkmagenta'),
                    labels = c('Bar or\nrestaurant',
                    'Church',
                    'University',
                    'Family',
                    'Friends',
                    'Neighbors',
                    'Online',
                    'High school\nor below',
                    'Work')) +
  theme(panel.background = element_rect(fill = NA),
        panel.grid.major = element_line(colour = "lightgray")) +
  scale_color_manual(values = 'black') +
  labs(y = NULL,
       x = 'Year couple met',
       title = 'Increasingly, we find partners among strangers rather than via introductions',
       fill = 'How couple met')

```


```{r}
fixed_cpl %>%
  mutate(pre_college = Church + Family + Neighbors + School,
         college_plus = Friends + College + Work) %>%
  select(Year, pre_college, college_plus, Bar_rest, Online) %>%
  gather(-Year, key = 'meeting_place', value = 'share') %>%
  mutate(meeting_place = as_factor(meeting_place)) %>%
  arrange(Year, meeting_place) %>%
  ggplot(mapping = aes(x = Year, y = share, fill = meeting_place)) +
  geom_col(color = 'black', size = 1) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  scale_fill_manual(values=c('dodgerblue', 'darkgray', 'forestgreen', 'orange'),
                    labels = c('Church, family,\nneighbors, or school',
                               'Friends, work,\nor university',
                               'Bar or restaurant',
                               'Online')) +
  # scale_fill_discrete(labels = c('Church, family,\nneighbors, or school',
  #                              'University,\nwork or friends',
  #                              'Bar or restaurant',
  #                              'Online')) +
  # 
  scale_color_manual(values = 'black') +
  labs(y = NULL,
       x = 'Year couple met',
       title = 'Singles shift from traditional to modern ways to meet partners',
       fill = 'How couple met') +
  theme(line = element_line(size = 2))
```


```{r}
fixed_cpl %>%
  gather(-Year, key = 'meeting_place', value = 'share') %>%
  arrange(Year, meeting_place) %>%
  ggplot(mapping = aes(x = Year, y = share, na.rm = T, fill = meeting_place)) +
  geom_area(color = 'black', size = 1) +
  scale_y_continuous(labels = percent_format(accuracy = 1)) +
  scale_fill_manual(values=c('red', 'orange', 'yellow', 'green4', 'turquoise', 'blue', 'slateblue', 'purple4', 'darkmagenta'),
                    labels = c('Bar or\nrestaurant',
                    'Church',
                    'University',
                    'Family',
                    'Friends',
                    'Neighbors',
                    'Online',
                    'High school\nor below',
                    'Work')) +
  theme(panel.background = element_rect(fill = NA),
        panel.grid.major = element_line(colour = "lightgray"),
        strip.text = element_blank(),
        panel.spacing = unit(1, "lines")) +
  scale_color_manual(values = 'black') +
  labs(y = NULL,
       x = 'Year couple met',
       title = 'Increasingly, we find partners among strangers rather than via introductions',
       fill = 'How couple met') +
  facet_wrap(facets = ~meeting_place, ncol = 3)
```


```{r}
fixed_cpl %>%
  mutate(pre_college = Church + Family + Neighbors + School,
         college_plus = Friends + College + Work,
         strangers = Bar_rest + Online,
         e_ratio = Online) %>%
  select(Year, pre_college, college_plus, strangers, e_ratio) %>%
  gather(-Year, -e_ratio, key = 'meeting_place', value = 'share') %>%
  mutate(meeting_place = as_factor(meeting_place)) %>%
  arrange(Year, meeting_place) %>%
  ggplot(mapping = aes(x = Year, y = share, fill = meeting_place, color = e_ratio)) +
  geom_col(size = 1) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  scale_fill_manual(values=c('dodgerblue', 'forestgreen', 'orange'),
                    labels = c('Church, family,\nneighbors, or school',
                               'Friends, work,\nor university',
                               'Online, bar,\nor restaurant')) +
  # scale_fill_discrete(labels = c('Church, family,\nneighbors, or school',
  #                              'University,\nwork or friends',
  #                              'Bar or restaurant',
  #                              'Online')) +
  # 
  scale_color_gradient(low = 'black', high = 'darkorange') +
  labs(y = NULL,
       x = 'Year couple met',
       title = 'Singles shift from traditional to modern ways to meet partners',
       fill = 'How couple met') +
  theme(line = element_line(size = 2),
        axis.ticks = element_blank())
```




```{r}
gun_data <- read.csv('c:\\Users\\Mario\\Desktop\\guns_deaths.csv')
  
gun_data %>%
  filter(deaths_pc < 0.0001) %>%
  ggplot(mapping = aes(x = guns_pc, y = deaths_pc, size = guns_pc)) +
  geom_point() +
  geom_smooth(method = 'lm')
  
```


```{r}
# https://www.washingtonpost.com/news/wonk/wp/2015/04/27/the-disturbing-differences-in-what-men-want-in-their-wives-and-their-daughters/
tribble(~'quality', ~'wife', ~'daughter',
        'Intelligent', 72, 81,
        'Attractive',45, 10,
        'Independent', 34, 66,
        'Sweet', 34, 19,
        'Strong', 30, 48,
        'Principled', 0, 35) %>%
  gather(-quality, key = 'woman', value = 'percent') %>%
  mutate(quality = as.factor(quality),
         woman = as.factor(woman)) %>%
  arrange(desc(percent)) %>%
  ggplot() +
  geom_col(aes(x = quality, y = percent, fill = woman), position = 'dodge', color = 'black', size = 1) +
  scale_fill_manual(values = c('dodgerblue', 'orange')) +
  labs(fill = 'Percent of men who say this quality is important in their:',
       x = NULL,
       y = NULL) +
  theme(legend.position = 'bottom')
```

