---
title: "ss_v_midclass"
author: "Mario"
date: 'Date created: `r Sys.Date()`'
output:
  html_notebook:
    code_folding: hide
    df_print: paged
    highlight: kate
    smart: yes
    theme: paper
    toc: no
  html_document:
    toc: no
---
# {.tabset} 

## abstract

ojfowj

## background

## setup

Install and load packages
```{r}

# install.packages('gapminder')
library(tidyverse); library(lubridate); library(gapminder)
```

Load poverty guideline data
```{r}

povertyline_hist <- read.csv(file = 'hstpov1.csv', header = T, na.strings = '***') %>%
  mutate(yr = year
         ,yr_mth = yr * 100 + 7) %>%
  select(yr_mth, X2_senior, X1_senior, X4_all)
```

Load social security cost of living adjustment data
```{r}

ss_cola <- read_delim(delim = ' '
             ,file = 'cola_1975-2019.txt'
             ,col_names = c('mth_name', 'yr', 'rmv', 'percent')) %>%
  mutate(mth_name = trimws(mth_name)
         ,mth = match(mth_name, month.name)
         ,yr_mth = yr*100 + mth) %>%
  select(yr_mth, percent)
```

Load social security historic benefits data
```{r}

socsec_hist <- read_csv(file = 'some_socsec.csv', col_names = T) %>%
  mutate(MonthYear = dmy(paste('1-', MonthYear))
         ,yr = year(MonthYear)
         ,mth = month(MonthYear)
         ,yr_mth = yr * 100 + mth
         ,ss_2 = Couple) %>%
  select(yr_mth, ss_2)
```

Load median income data
```{r}

mdn_y_hist <- read.csv(file = 'mdn_house-fam_y.csv', na.strings = 'NULL') %>%
  mutate(yr = if_else(year(mdy(DATE)) < 2020
                      ,year(mdy(DATE))
                      ,year(mdy(DATE)) - 100)
         ,mth = month(mdy(DATE))
         ,yr_mth = yr * 100 + mth) %>%
  select(yr_mth, mdn_house_y, mdn_fam_y)
```

First, join socsec cola and benefits data to fill missing years
```{r}

socsec_hist %>%
  full_join(p)
```



