---
title: "R Notebook"
output: html_notebook
---

Study of a plinko board.

Load some packages

```{r message=FALSE}
library(ggalt); library(tidyverse); library(lubridate); library(stringr); library(scales)
```


Import some data

```{r message=FALSE}
results <- read_csv('results.csv', col_types = 'iiii')
```


```{r}
results %>%
  group_by(adj_start) %>%
  # filter(adj_start %in% c(1,8)) %>%
  summarize(ct = n(),
            mean_end = mean(adj_end, na.rm = T),
            std_end = sd(adj_end, na.rm = T)) %>%
  ggplot(mapping = aes(x = adj_start, y = std_end)) +
  geom_point(mapping = aes(size = ct)) +
  # geom_count() +
  geom_smooth(method = 'loess')
  # geom_crossbar(mapping = aes(x = adj_start, ymin = mean_end - std_end, ymax = mean_end + std_end))
```


```{r}
results %>%
  group_by(adj_start) %>%
  summarize(stddev = sd(adj_end),
            mean_end = mean(adj_end)) %>%
  # summarize(mean_end = mean(adj_end, na.rm = T),
  #           std_end = sd(adj_end, na.rm = T)) %>%
  ggplot(mapping = aes(x = adj_start, y = stddev)) +
  geom_point() +
  # geom_count() +
  geom_smooth(method = 'lm')
  # geom_crossbar(mapping = aes(x = adj_start, ymin = mean_end - std_end, ymax = mean_end + std_end))
```
