---
title: "Assignment 2"
author: ~~Hari Subhash~~ Mario 
date: "Date created: `r Sys.Date()`"
output:
  html_notebook:
    highlight: kate
    smart: yes
    theme: cosmo
    code_folding: show
    df_print: paged
    toc: true
    toc_depth: 2
---

## Abstract

Unpredictable flight delays are a costly problem, forcing travelers to choose between . In 2013, flights from the three New York area airports alone saw aggregate delays of half a million minutes.

## Background

**PROBLEM:** Here, the problem is that flight delays are unpredictable. Not only that, mis-timing your ride to the airport could be costly; Arrive late and you may miss your flight altogether, but arrive early and you'll spend even more uncomfortable, unproductive time at the gate

**GOAL:** My ultimate goal is to be able to best predict a flight's departure delay. In an ideal world, all flights would simply leave on time. In a second-best world, each airline would contact travelers directly with flight delay information that was accurate and timely enough to be actionable. Alas, neither of those are the case and so in the world we live in, my goal is to better predict delay using weather and flight data.

**HYPOTHESIS:** In looking for a relationship that helps estimate the departure delay of a given flight, I'll effectively be looking to disprove the converse -- namely, that *no* available weather or flight data shares a relationship with flight delay. 


## Setting up

```{r}
### Install packages, as needed 
# install.packages('tidyverse') 
# install.packages('skimr') 
# install.package('lubridate')
# install.packages('Hmisc')

library(tidyverse); library(skimr); library(nycflights13); library(lubridate); library(Hmisc)

flt_wx <- flights %>%
  left_join(weather,by = c('origin','time_hour')) %>%
  mutate(wkday = wday(as.Date(time_hour)) 
        ,near_20 = abs(hour-20)
		    ,decness = abs(month.x-5.99)
		    ,mo_day = mdy(paste(month.x,day.x,2013))) %>%
  group_by(mo_day) %>%
  mutate(day_flt = length(mo_day)) %>%
  ungroup() %>%
  select(dep_delay,temp:decness,day_flt:wkday_effect)



flt_wx

flt_wx %>%
  cor(use = 'pairwise.complete.obs',method = 'pearson') %>%
  round(2) %>%
  as.data.frame() %>%
  select(1) %>%
  cbind(rownames(.),.) %>%
  filter(dep_delay > 0 & dep_delay < 1) %>%
  arrange(desc(dep_delay))

flights %>%
  mutate(diff_20 = abs(hour-20)) %>% 
  select(dep_delay,hour,diff_20) %>%
  group_by(diff_20) %>%
  summarize(mean_delay = mean(dep_delay, na.rm = T)) %>%
#  arrange(desc(mean_delay)) %>%
#  cor(use = 'pairwise.complete.obs',method = 'pearson')
#
  ggplot(data = .,mapping = aes(x=diff_20,y=mean_delay)) +
  geom_point() +
  geom_smooth(method = lm)

md  <- function(x){flights %>%
  mutate(mthness = abs(x-month(time_hour))) %>%
  select(dep_delay,mthness) %>%
  cor(use = 'pairwise.complete.obs',method = 'pearson')}


flights %>%
  filter(dep_delay>0) %>%
  group_by(time_hour) %>%
  summarise(hr_flt = length(sched_dep_time),mean_delay = mean(dep_delay,na.rm = T)) %>%
  select(hr_flt,mean_delay) %>%
  ggplot(data = .,mapping = aes(x=hr_flt,y=mean_delay)) +
  geom_point() +
  geom_smooth(method = lm)

  
    cor(use = 'pairwise.complete.obs',method = 'pearson')



#
  ggplot(data = .,mapping = aes(x=wkday,y=mean_delay)) +
  geom_point() +
  geom_smooth(method = loess)
  

flights %>%
  mutate(diff_20 = abs(hour-20)) %>% 
  select(dep_delay,hour,diff_20) %>%
  group_by(diff_20) %>%
  summarize(mean_delay = mean(dep_delay, na.rm = T))

    
```

